### PR TITLE
Fetch unreleased data only if required internally (gRPC changes)

### PR DESCRIPTION
**Pull request by bilalebi**
### JIRA Ticket
https://www.ebi.ac.uk/panda/jira/browse/EA-1109

### Changes
Update the API to fetch unreleased data only if required internally using `UNRELEASED_DATA_ONLY` environment variable.

### Related PR:
https://github.com/Ensembl/ensembl-metadata-api/pull/36

### CODE REVIEW

**Comment by bilalebi** [comment]
> I am not about the meaning of this flag :
> 
>     * is it to "force every" data retrieve to be "unreleased"?
> 
>     * is it to authorize the request not to set a release, therefore returning unreleased data as well?
>       The name is not clear to me

It's the latter, to give you some context, Compara wanted to have the possibility to fetch unreleased data; before adding this flag, any user (public or internal) could fetch both released and unreleased data.

The aim of this flag is to allow us to internally fetch unreleased data by setting it to `true`.

I'm thinking of a scenario where, for example, Compara will have their own internal instance where they can switch `UNRELEASED_DATA_ONLY` on and off.

**Comment by marcoooo** [comment]
> > I am not about the meaning of this flag :
> > ```
> > * is it to "force every" data retrieve to be "unreleased"?
> > 
> > * is it to authorize the request not to set a release, therefore returning unreleased data as well?
> >   The name is not clear to me
> > ```
> 
> ~It's the latter~, to give you some context, Compara wanted to have the possibility to fetch unreleased data; before adding this flag, any user (public or internal) could fetch both released and unreleased data.
> 
> The aim of this flag is to allow us to internally fetch unreleased data by setting it to `true`.
> 
> I'm thinking of a scenario where, for example, Compara will have their own internal instance where they can switch `UNRELEASED_DATA_ONLY` on and off.
> 
> > Also as you stated, once it's ON, it will retrieve only unreleased data.

Ok, I'll need to discuss it a bit further, because this use case is essentially "internal". any public facing service shouldn't allow queries without release set. Even compara.

**Comment by marcoooo** [comment]
> > > I am not about the meaning of this flag :
> > > ```
> > > * is it to "force every" data retrieve to be "unreleased"?
> > > 
> > > * is it to authorize the request not to set a release, therefore returning unreleased data as well?
> > >   The name is not clear to me
> > > ```
> > 
> > 
> > ~It's the latter~, to give you some context, Compara wanted to have the possibility to fetch unreleased data; before adding this flag, any user (public or internal) could fetch both released and unreleased data.
> > The aim of this flag is to allow us to internally fetch unreleased data by setting it to `true`.
> > I'm thinking of a scenario where, for example, Compara will have their own internal instance where they can switch `UNRELEASED_DATA_ONLY` on and off.
> > > Also as you stated, once it's ON, it will retrieve only unreleased data.
> 
> Ok, I'll need to discuss it a bit further, because this use case is essentially "internal". any public facing service shouldn't allow queries without release set. Even compara.

The way I would see it would be a combination of two parameters:
- ALLOW_UNRELEASED - by its name you figured it out
- DEFAULT_RELEASE (_NUMBER?) to  set a default value if a request is not setting one. 
This way: We allow unreleased data retrieval, and even though, we'll set a default one if it's not set in the request.

**Comment by bilalebi** [comment]
@marcoooo this PR is ready to be merged, I just need to update the `metadata-api` dependency to point to `main` once this https://github.com/Ensembl/ensembl-metadata-api/pull/36 PR is merged.

**Review by marcoooo — APPROVED** [review]

**Pull request merged**
