### PR TITLE
Get Detailed genome info data

### PR DESCRIPTION
**Pull request by bilalebi**
### JIRA Tickets
* https://www.ebi.ac.uk/panda/jira/browse/EA-1105
* https://www.ebi.ac.uk/panda/jira/browse/EA-1107
* https://www.ebi.ac.uk/panda/jira/browse/EA-1098

### Changes
Extend the metadata gRPC schema to provide a procedure web team can use to populate [Ensembl's species page](https://beta.ensembl.org/species/grch38) with assembly information

### Example 1
Request
```
{
	"genome_uuid": "a7335667-93e7-11ec-a39d-005056b38ce3"
}
```

Response
```
{
	"genome_uuid": "a7335667-93e7-11ec-a39d-005056b38ce3",
	"assembly": {
		"accession": "GCA_000001405.29",
		"name": "GRCh38.p14",
		"ucsc_name": "hg38",
		"level": "chromosome",
		"ensembl_name": "GRCh38.p14",
		"assembly_uuid": "fd7fea38-981a-4d73-a879-6f9daef86f08",
		"is_reference": true
	},
	"taxon": {
		"common_name": [],
		"taxonomy_id": 9606,
		"scientific_name": "Homo sapiens",
		"strain": ""
	},
	"created": "2023-09-22 15:04:45",
	"organism": {
		"common_name": "human",
		"strain": "",
		"scientific_name": "Homo sapiens",
		"ensembl_name": "homo_sapiens",
		"scientific_parlance_name": "Human",
		"organism_uuid": "1d336185-affe-4a91-85bb-04ebd73cbb56",
		"strain_type": "",
		"taxonomy_id": 9606,
		"species_taxonomy_id": 9606
	},
	"attributes_info": {
		"genebuild_method": "",
		"genebuild_last_geneset_update": "",
		"genebuild_version": "",
		"annotation_provider_name": "",
		"annotation_provider_url": "",
		"assembly_level": "chromosome",
		"assembly_date": "2013-12",
		"sample_gene_param": "",
		"sample_location_param": ""
	},
	"related_assemblies_count": 99,
	"release": {
		"release_version": 0,
		"release_date": "Unreleased",
		"release_label": "Unreleased",
		"is_current": false,
		"site_name": "Unknown (not released yet)",
		"site_label": "Unknown (not released yet)",
		"site_uri": "Unknown (not released yet)"
	}
}
```

### Example 2
Request
```
{
	"genome_uuid": "9caa2cae-d1c8-4cfc-9ffd-2e13bc3e95b1"
}
```

Response
```
{
	"genome_uuid": "9caa2cae-d1c8-4cfc-9ffd-2e13bc3e95b1",
	"assembly": {
		"accession": "GCA_018473315.1",
		"name": "HG03540.alt.pat.f1_v2",
		"ucsc_name": "",
		"level": "primary_assembly",
		"ensembl_name": "HG03540.alt.pat.f1_v2",
		"assembly_uuid": "9d2dc346-358a-4c70-8fd8-3ff194246a76",
		"is_reference": false
	},
	"taxon": {
		"common_name": [],
		"taxonomy_id": 9606,
		"scientific_name": "Homo sapiens",
		"strain": "Gambian in Western Division"
	},
	"created": "2023-09-22 15:02:00",
	"organism": {
		"common_name": "human",
		"strain": "Gambian in Western Division",
		"scientific_name": "Homo sapiens",
		"ensembl_name": "homo_sapiens_HG03540",
		"scientific_parlance_name": "Human",
		"organism_uuid": "18bd7042-d861-4a10-b5d0-68c8bccfc87e",
		"strain_type": "population",
		"taxonomy_id": 9606,
		"species_taxonomy_id": 9606
	},
	"attributes_info": {
		"genebuild_method": "",
		"genebuild_last_geneset_update": "",
		"genebuild_version": "",
		"annotation_provider_name": "",
		"annotation_provider_url": "",
		"assembly_level": "scaffold",
		"assembly_date": "2021-05",
		"sample_gene_param": "",
		"sample_location_param": ""
	},
	"related_assemblies_count": 99,
	"release": {
		"release_version": 0,
		"release_date": "Unreleased",
		"release_label": "Unreleased",
		"is_current": false,
		"site_name": "Unknown (not released yet)",
		"site_label": "Unknown (not released yet)",
		"site_uri": "Unknown (not released yet)"
	}
}
```

### Related PR
https://github.com/Ensembl/ensembl-metadata-api/pull/40

### CODE REVIEW

**Comment by jonk-ebi** [comment]
This is something that has came out over the last few days so apologies for a late change. 

If strain or strain_type is null or empty then both should be empty. So for the example above both strain and strain_type should be ""

**Comment by bilalebi** [comment]
> This is something that has came out over the last few days so apologies for a late change.
> 
> If strain or strain_type is null or empty then both should be empty. So for the example above both strain and strain_type should be ""

Thank you for letting me know, no worries, I will update the code.

**Comment by azangru** [comment]
Out of curiosity, what does the `release` block mean in the example response? Given genome uuid, what does release_version mean? What do `site_name`, `site_label` and `site_url` mean in the new world of only one Ensembl site?

**Comment by bilalebi** [comment]
> Out of curiosity, what does the `release` block mean in the example response? Given genome uuid, what does release_version mean? What do `site_name`, `site_label` and `site_url` mean in the new world of only one Ensembl site?

@azangru, this is an example of how it might look like once the data is released:
```
"release": {
  "releaseVersion": 108.0,
  "releaseDate": "2023-05-15",
  "releaseLabel": "Beta Release 1",
  "isCurrent": True,
  "siteName": "Ensembl",
  "siteLabel": "Ensembl Genome Browser",
  "siteUri": "https://beta.ensembl.org"
}
```
I don't want to say something wrong/stupid; @marcoooo might be able to shed more light on this.

**Comment by marcoooo** [comment]
> > Out of curiosity, what does the `release` block mean in the example response? Given genome uuid, what does release_version mean? What do `site_name`, `site_label` and `site_url` mean in the new world of only one Ensembl site?
> 
> @azangru, this is an example of how it might look like once the data is released:
> 
> ```
> "release": {
>   "releaseVersion": 108.0,
>   "releaseDate": "2023-05-15",
>   "releaseLabel": "Beta Release 1",
>   "isCurrent": True,
>   "siteName": "Ensembl",
>   "siteLabel": "Ensembl Genome Browser",
>   "siteUri": "https://beta.ensembl.org"
> }
> ```
> 
> I don't want to say something wrong/stupid; @marcoooo might be able to shed more light on this.

yes, this is what it would look like once data are released (which is not the case in test data? but might be a good idea to introduce this in tests @bilalebi )

**Comment by bilalebi** [comment]
> > > Out of curiosity, what does the `release` block mean in the example response? Given genome uuid, what does release_version mean? What do `site_name`, `site_label` and `site_url` mean in the new world of only one Ensembl site?
> > 
> > 
> > @azangru, this is an example of how it might look like once the data is released:
> > ```
> > "release": {
> >   "releaseVersion": 108.0,
> >   "releaseDate": "2023-05-15",
> >   "releaseLabel": "Beta Release 1",
> >   "isCurrent": True,
> >   "siteName": "Ensembl",
> >   "siteLabel": "Ensembl Genome Browser",
> >   "siteUri": "https://beta.ensembl.org"
> > }
> > ```
> > 
> > 
> > I don't want to say something wrong/stupid; @marcoooo might be able to shed more light on this.
> 
> yes, this is what it would look like once data are released (which is not the case in test data? but might be a good idea to introduce this in tests @bilalebi )

Yes @marcoooo they are already there, I got that example [from tests](https://github.com/Ensembl/ensembl-metadata-service/blob/afd0944be619bb1fc4d9b99e51e8d1b55be1247d/src/tests/test_protobuf_msg_factory.py#L61C16-L61C16) :)

**Review by marcoooo — APPROVED** [review]

**Pull request merged**
